spring:
  application:
    name: League-of-Legends
  datasource:
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  config:
    import: optional:file:.env[.properties]
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE

resilience4j:
  retry:
    instances:
      ddragon-client:
        max-attempts: ${RESILIENCE4J_MAX_ATTEMPTS}
        wait-duration: ${RESILIENCE4J_WAIT_DURATION}
        enable-exponential-backoff: ${RESILIENCE4J_ENABLE_EXPONENTIAL_BACKOFF}
        retry-exceptions:
          - feign.FeignException # Só tenta de novo se for erro do Feign
          - java.io.IOException
        ignore-exceptions:
          - io.github.riotgames.leagueoflegends.domain.exception.BusinessException
ddragon:
  api:
    url: ${DDRAGON_API_URL:https://ddragon.leagueoflegends.com}